name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar entorno
        run: echo "Configurar dependencias"

      - name: Ejecutar tests
        run: echo "Ejecutar pruebas"
